import * as React from 'react';
import PropTypes from 'prop-types';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Grid2';

import GoBackButton from '../components/GoBackButton';
import SummaryCardActions from '../components/SummaryCardActions';
import SummaryCardDocuments from '../components/SummaryCardDocuments';
import CaseSummary from '../components/CaseSummary';
import SuccessfulCases from '../components/SuccessfulCases';

function TabPanel(props) {
  const { children, value, index, ...other } = props;

  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`vertical-tabpanel-${index}`}
      aria-labelledby={`vertical-tab-${index}`}
      {...other}
    >
      {value === index && (
        <Box sx={{ p: 0,  }}>
          <div className="tabContent">{children}</div>
        </Box>
      )}
    </div>
  );
}

TabPanel.propTypes = {
  children: PropTypes.node,
  index: PropTypes.number.isRequired,
  value: PropTypes.number.isRequired,
};

function tabsProps(index) {
  return {
    id: `vertical-tab-${index}`,
    'aria-controls': `vertical-tabpanel-${index}`,
  };
}

export default function VerticalTabs() {
  const [value, setValue] = React.useState(0);

  const handleChange = (event, newValue) => {
    setValue(newValue);
  };

  return (
    <>
      <GoBackButton />

      <Box
        sx={{ flexGrow: 1, display: 'flex' }}
      >
        <Grid className="container" container spacing={0} size={{ xs: 12, md: 12, lg: 12 }}>
          <Grid size={{ xs: 12, lg: 2 }}>
            <Tabs className="supportTools"
              orientation="vertical"
              variant="standard"
              value={value}
              onChange={handleChange}
              aria-label="Vertical tabs"
              sx={{ borderRight: 1, borderColor: 'divider' }}
            >
              <Tab label="Case Summary" {...tabsProps(0)} />
              <Tab label="Item Two" {...tabsProps(1)} />
              <Tab label="Item Three" {...tabsProps(2)} />
              <Tab label="Item Four" {...tabsProps(3)} />
              <Tab label="Item Five" {...tabsProps(4)} />
              <Tab label="Item Six" {...tabsProps(5)} />
              <Tab label="Item Seven" {...tabsProps(6)} />
            </Tabs>
          </Grid>
          <Grid size={{ xs: 12, lg: 10 }}>
            <TabPanel className="tabPanel" value={value} index={0}>
              <Grid container spacing={4}>
                <Grid size={{ xs: 12, lg: 12 }}>
                  <h2>Your case details</h2>
                  <p>Below, you'll find an overview of your journey, a summary of your case, similar successful cases, and any relevant videos, all analysed and generated by our AI system based on your uploaded file.</p>
                </Grid>
              </Grid>
              <Grid container spacing={4}>
                <Grid size={{ xs: 12, lg: 6 }}>
                  <SummaryCardActions />
                </Grid>
                <Grid size={{ xs: 12, lg: 6 }}>
                  <SummaryCardDocuments />
                </Grid>
              </Grid>
              <Grid container spacing={12}>
                <Grid size={{ xs: 12, lg: 8 }}>
                  <CaseSummary />
                  <SuccessfulCases />
                </Grid>
                <Grid size={{ xs: 12, lg: 4 }}>
                  <h2 className='largeText mt-4'>Pathway</h2>
                </Grid>
              </Grid>
            </TabPanel>
            <TabPanel className="tabPanel" value={value} index={1}>
              Item Two
            </TabPanel>
            <TabPanel className="tabPanel" value={value} index={2}>
              Item Three
            </TabPanel>
            <TabPanel className="tabPanel" value={value} index={3}>
              Item Four
            </TabPanel>
            <TabPanel className="tabPanel" value={value} index={4}>
              Item Five
            </TabPanel>
            <TabPanel className="tabPanel" value={value} index={5}>
              Item Six
            </TabPanel>
            <TabPanel className="tabPanel" value={value} index={6}>
              Item Seven
            </TabPanel>
          </Grid>
        </Grid>
      </Box>
    </>
  );
}