import * as React from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import './SupportTools.css';

export default function SupportTools() {
  const navigate = useNavigate();
  const { caseId } = useParams();
  
  // Navigation function for all services including case details
  const navigateToService = (e, serviceName) => {
    e.preventDefault();
    if (caseId) {
      // Special handling for case details which has a different URL pattern
      if (serviceName === 'case-details') {
        navigate(`/case-details/${caseId}`);
      } else {
        navigate(`/case-details/${caseId}/service/${serviceName}`);
      }
    } else {
      console.warn('No case ID available for navigation');
      // Fallback to basic navigation without caseId
      navigate(`/${serviceName}`);
    }
  };

  return (
    <>
      <ul className="supportTools">
        <li className='btn-blue caseDetails'>
          <a href="#" onClick={(e) => navigateToService(e, 'case-details')}>Case details</a>
          <div className='tooltip'>
            Review an overview of your case, your recommended journey, similar successful cases, and relevant videos, all analysed and generated by our AI system based on your uploaded file.
          </div>
        </li>
        <li className='btn-orange benefits'>
          <a href="#" onClick={(e) => navigateToService(e, 'better-off')}>Eligible Benefits</a>
          <div className='tooltip'>
            Calculate how changes in your circumstances might affect your finances. Get a clear picture of your financial situation and make informed decisions.
          </div>
        </li>
        <li className='btn-maroon adviceFinder'>
          <a href="#" onClick={(e) => navigateToService(e, 'advice-finder')}>Advice Finder</a>
          <div className='tooltip'>
            Easily find legal advice and resources tailored to your family law situation. Connect with professionals and access guidance on parenting, finances, and other legal matters.
          </div>
        </li>
        <li className='btn-teal wyserAssist'>
          <a href="#" onClick={(e) => navigateToService(e, 'transcribe')}>Transcribe</a>
          <div className='tooltip'>
            Get AI-powered assistance with your case. Our transcription service allows you to upload audio files and add them to your case documents.
          </div>
        </li>
        <li className='btn-yellow financePlanner'>
          <a href="#" onClick={(e) => navigateToService(e, 'finance-planner')}>Finance Planner</a>
          <div className='tooltip'>
            Track and manage financial arrangements, including support payments and asset division. Stay organized and ensure clarity in your financial commitments during your family law case.
          </div>
        </li>
        <li className='btn-green parentPlanner'>
          <a href="#" onClick={(e) => navigateToService(e, 'parent-planner')}>Parent Planner</a>
          <div className='tooltip'>
            Organise and track parenting schedules, agreements, and key events. Coordinate time-sharing and ensure smooth communication for consistent child care.
          </div>
        </li>
        <li className='btn-pink homesAndAssets'>
          <a href="#" onClick={(e) => navigateToService(e, 'homes-and-assets')}>Homes & Assets</a>
          <div className='tooltip'>
            Manage and track the division of assets, including the family home and other property. Stay organized and ensure fair distribution in line with your family law case.
          </div>
        </li>
        <li className='btn-purple findRepresentative'>
          <a href="#" onClick={(e) => navigateToService(e, 'find-a-representative')}>Find Legal Help</a>
          <div className='tooltip'>
            Search for qualified legal representatives who specialise in family law. Find the right support to guide you through your case and protect your interests.
          </div>
        </li>
        <li className='btn-cobalt mentalHealth'>
          <a href="#" onClick={(e) => navigateToService(e, 'mental-health')}>Mental Health</a>
          <div className='tooltip'>
            Access resources and support for mental health. Find guidance, professionals, and services to help you manage your well-being during challenging times.
          </div>
        </li>
      </ul>
    </>
  );
}
