import * as React from 'react';

import './SupportTools.css';

export default function SupportTools() {
  return (
    <>
      <ul className="supportTools">
        <li className='btn-blue caseDetails'>
          <a href="/case-details">Case details</a>
          <div className='tooltip'>
            Review an overview of your case, your recommended journey, similar successful cases, and relevant videos, all analysed and generated by our AI system based on your uploaded file.
          </div>
        </li>
        <li className='btn-green parentPlanner'>
          <a href="/parent-planner">Parent planner</a>
          <div className='tooltip'>
            Organise and track parenting schedules, agreements, and key events. Coordinate time-sharing and ensure smooth communication for consistent child care.
          </div>
        </li>
        <li className='btn-yellow financePlanner'>
          <a href="/finance-planner">Finance planner</a>
          <div className='tooltip'>
            Track and manage financial arrangements, including support payments and asset division. Stay organized and ensure clarity in your financial commitments during your family law case.
          </div>
        </li>
        <li className='btn-orange benefits'>
          <a href="/benefits">Benefits</a>
          <div className='tooltip'>
            Track and manage benefits related to your family law case, including child benefits, healthcare, and other entitlements. Stay organized and ensure timely access to necessary resources for you and your child.
          </div>
        </li>
        <li className='btn-maroon adviceFinder'>
          <a href="advice-finder">Advice finder</a>
          <div className='tooltip'>
            Easily find legal advice and resources tailored to your family law situation. Connect with professionals and access guidance on parenting, finances, and other legal matters.
          </div>
        </li>
        <li className='btn-pink homesAndAssets'>
          <a href="/homes-and-assets">Homes and assets</a>
          <div className='tooltip'>
            Manage and track the division of assets, including the family home and other property. Stay organized and ensure fair distribution in line with your family law case.
          </div>
        </li>
        <li className='btn-purple findRepresentative'>
          <a href="/find-a-representative">Find a representative</a>
          <div className='tooltip'>
            Search for qualified legal representatives who specialise in family law. Find the right support to guide you through your case and protect your interests.
          </div>
        </li>
        <li className='btn-cobalt mentalHealth'>
          <a href="/mental-health">Mental health</a>
          <div className='tooltip'>
            Access resources and support for mental health. Find guidance, professionals, and services to help you manage your well-being during challenging times.
          </div>
        </li>
        <li className='btn-blue voiceOfTheChild'>
          <a href="/voice-of-the-child">Voice of the child</a>
          <div className='tooltip'>
            Ensure your child’s views and preferences are heard and considered in family law decisions. This tool helps facilitate communication and supports the child’s well-being throughout the process.
          </div>
        </li>
      </ul>
    </>
  );
}